[package]
name = "telemetry-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
libfuzzer-sys = "0.4.6"
telemetry = { path = "crates/telemetry" }

[[bin]]
name = "telemetry_parser"
path = "fuzz_targets/telemetry_parser.rs"
